// <auto-generated />
using System;
using ERPHasseb.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERPHasseb.DAL.Migrations
{
    [DbContext(typeof(HasseebContext))]
    partial class HasseebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERPHasseb.DAL.Entities.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountDesc");

                    b.Property<string>("AccountName");

                    b.Property<int?>("AccountNatureID");

                    b.Property<string>("AccountSerial");

                    b.Property<bool>("Active");

                    b.Property<DateTime>("AddDate");

                    b.Property<int>("GroupOrder");

                    b.Property<bool>("IsMain");

                    b.Property<int?>("ParentAccountID");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountNatureID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ERPHasseb.DAL.Entities.AccountNature", b =>
                {
                    b.Property<int>("AccountNatureID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNatureName");

                    b.HasKey("AccountNatureID");

                    b.ToTable("AccountNatures");
                });

            modelBuilder.Entity("ERPHasseb.DAL.Entities.Account", b =>
                {
                    b.HasOne("ERPHasseb.DAL.Entities.AccountNature")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountNatureID");
                });
#pragma warning restore 612, 618
        }
    }
}
